#!/usr/bin/python3
def raise_exception():
    x = "10"
    y = 5

    result = x/y

    return result
